name: hazari_bagh_market
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # üåç REQUIRED FOR LOCALIZATION
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  animations: ^2.1.1
  tap_to_expand: ^0.7.2
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.3
  shared_preferences: ^2.5.4
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  video_player: ^2.10.1
  visibility_detector: ^0.4.0+2
  animated_notch_bottom_bar: ^1.0.4
  cuberto_bottom_bar: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  #  THIS IS THE CORRECT PLACE
  generate: true

  assets:
    - assets/images/
    - assets/Icons/
    - assets/Videos/shopAds.mp4
